spring:
  application:
    name: "DonorEngine"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Open123$
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size:  10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
info:
  app:
    name: Donor Engine
    description: This is donor engine of donor management system from MiniERP suit
    version: 1.0.0
    author: S V Krishna Reddy
    email: info@brtycode.com