server:
    port: 9090
spring:
    application:
        name: BrytGateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
    instance:
        instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
        prefer-ip-address: true
