CREATE TABLE ORGANISATION_TYPE
(
    LINE_ID SERIAL PRIMARY KEY,
    ORG_TYPE VARCHAR(32) UNIQUE NOT NULL,
    ORG_TYPE_DESC VARCHAR(512),
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    LAST_UPDATED_DATE DATE DEFAULT CURRENT_DATE,
    UPSERT_BY VARCHAR(256)
);

CREATE TABLE ORGANISATION
(
    LINE_ID SERIAL PRIMARY KEY,
    ORG_ID VARCHAR(256) UNIQUE,
    ORG_NAME VARCHAR(256),
    ORG_UNAME VARCHAR(32) UNIQUE,
    ORG_TYPE VARCHAR(32) REFERENCES ORGANISATION_TYPE(ORG_TYPE),
    ORG_ADDRESS VARCHAR(512),
    ORG_PHONE_NO VARCHAR(32),
    ORG_EMAIL_ID VARCHAR(256),
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    LAST_UPDATED_DATE DATE DEFAULT CURRENT_DATE,
    UPSERT_BY VARCHAR(256)
);